2024-12-08 08:53:08,375:DEBUG:certbot._internal.main:certbot version: 3.0.1
2024-12-08 08:53:08,375:DEBUG:certbot._internal.main:Location of certbot entry point: /home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/bin/certbot
2024-12-08 08:53:08,375:DEBUG:certbot._internal.main:Arguments: ['--authenticator', 'dns-hostingnl', '-d', 'tech7fox.nl', '--config-dir', './certbot_stuff/', '--work-dir', 'certbot_stuff/', '--logs-dir', 'certbot_stuff/']
2024-12-08 08:53:08,375:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-hostingnl,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-12-08 08:53:08,380:DEBUG:certbot._internal.log:Root logging level set at 30
2024-12-08 08:53:08,380:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-hostingnl and installer None
2024-12-08 08:53:08,380:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-hostingnl
Description: Obtain certificates using a DNS TXT record (if you are using Hostingnl for DNS).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='dns-hostingnl', value='certbot_dns_hostingnl._internal.dns_hostingnl:Authenticator', group='certbot.plugins')
Initialized: <certbot_dns_hostingnl._internal.dns_hostingnl.Authenticator object at 0x7f8da88f90d0>
Prep: True
2024-12-08 08:53:08,380:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_hostingnl._internal.dns_hostingnl.Authenticator object at 0x7f8da88f90d0> and installer None
2024-12-08 08:53:08,380:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-hostingnl, Installer None
2024-12-08 08:53:08,421:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2100827347', new_authzr_uri=None, terms_of_service=None), 3cfbde432f4e580690be996c3ac17825, Meta(creation_dt=datetime.datetime(2024, 12, 8, 7, 51, 56, tzinfo=datetime.timezone.utc), creation_host='ThinkPad-P16s', register_to_eff=None))>
2024-12-08 08:53:08,423:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-12-08 08:53:08,424:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-12-08 08:53:09,095:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/11" 200 746
2024-12-08 08:53:09,096:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 07:53:08 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "yi9RLJy0Xs8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2024-12-08 08:53:09,099:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): e6.o.lencr.org:80
2024-12-08 08:53:09,329:DEBUG:urllib3.connectionpool:http://e6.o.lencr.org:80 "POST / HTTP/11" 200 344
2024-12-08 08:53:09,329:DEBUG:certbot.ocsp:OCSP response for certificate /home/jordyk/repositories/personal/certbot-dns-hostingnl/certbot_stuff/archive/tech7fox.nl/cert1.pem is signed by the certificate's issuer.
2024-12-08 08:53:09,330:DEBUG:certbot.ocsp:OCSP certificate status for /home/jordyk/repositories/personal/certbot-dns-hostingnl/certbot_stuff/archive/tech7fox.nl/cert1.pem is: OCSPCertStatus.GOOD
2024-12-08 08:53:09,331:DEBUG:certbot._internal.display.obj:Notifying user: Certificate not yet due for renewal
2024-12-08 08:53:12,248:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/_internal/main.py", line 1876, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/_internal/main.py", line 1571, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/_internal/main.py", line 362, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/_internal/main.py", line 392, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/_internal/main.py", line 337, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordyk/repositories/personal/certbot-dns-hostingnl/vendor/lib/python3.12/site-packages/certbot/_internal/main.py", line 293, in _handle_identical_cert_request
    raise errors.Error(
certbot.errors.Error: Operation canceled. You may re-run the client.
2024-12-08 08:53:12,249:ERROR:certbot._internal.log:Operation canceled. You may re-run the client.
